# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170502_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
