# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 17:17
from __future__ import unicode_literals

from django.db import migrations
import csv

def add_books(apps, schema_editor):

    Book = apps.get_model("app", "Book")
    with open('authors.csv') as csvfile:
        books = csv.reader(csvfile, delimiter=',', quotechar= '|')
        for book in books:
            new_book = Book.objects.create(name=book[0],author=book[1],pages=int(book[2]),rating=float(book[3]))
            new_book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170502_1716'),
    ]

    operations = [
    migrations.RunPython(add_books),
    ]
